"""add admin role

Revision ID: ee0cd64ccfb1
Revises: 
Create Date: 2025-12-24 16:38:52.976410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0cd64ccfb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.alter_column('hostel',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('room_no',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('room_no',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('hostel',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('role')

    # ### end Alembic commands ###
